/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import modele.Etablissement;
import org.hibernate.*;
import org.hibernate.InstantiationException;


/**
 *
 * @author Maxence
 */
public class pEtablissementAjout extends javax.swing.JFrame {

    /**
     * Creates new form pEtablissementAjout
     */
    public pEtablissementAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLid = new javax.swing.JLabel();
        jLnom = new javax.swing.JLabel();
        jLadresse = new javax.swing.JLabel();
        jLcodepostal = new javax.swing.JLabel();
        jLville = new javax.swing.JLabel();
        jLtelephone = new javax.swing.JLabel();
        jLmail = new javax.swing.JLabel();
        jLtype = new javax.swing.JLabel();
        jLresciv = new javax.swing.JLabel();
        jLresnom = new javax.swing.JLabel();
        jLresprenom = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jTnom = new javax.swing.JTextField();
        jTadresse = new javax.swing.JTextField();
        jTcodepostal = new javax.swing.JTextField();
        jTville = new javax.swing.JTextField();
        jTtelephone = new javax.swing.JTextField();
        jTmail = new javax.swing.JTextField();
        jTtype = new javax.swing.JTextField();
        jTresciv = new javax.swing.JTextField();
        jTresnom = new javax.swing.JTextField();
        jTresprenom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLid.setText("Identifiant");

        jLnom.setText("Nom");

        jLadresse.setText("Adresse Rue");

        jLcodepostal.setText("Code Postal");

        jLville.setText("Ville");

        jLtelephone.setText("Telephone");

        jLmail.setText("Mail");

        jLtype.setText("Type");

        jLresciv.setText("Civilité ");

        jLresnom.setText("Nom");

        jLresprenom.setText("Prenom");

        jLabel12.setText("Etablissement");

        jLabel13.setText("Responsable");

        jTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidActionPerformed(evt);
            }
        });

        jButton1.setText("Ajout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(145, 145, 145)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLadresse)
                                    .add(jLnom)
                                    .add(jLid)
                                    .add(jLresnom)
                                    .add(jLresciv)
                                    .add(jLtype)
                                    .add(jLmail)
                                    .add(jLtelephone)
                                    .add(jLville)
                                    .add(jLresprenom)
                                    .add(jLcodepostal))
                                .add(114, 114, 114))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel13)
                                .add(24, 24, 24)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(jTresprenom)
                            .add(jTresnom)
                            .add(jTresciv)
                            .add(jTtype)
                            .add(jTmail)
                            .add(jTtelephone)
                            .add(jTville)
                            .add(jTcodepostal)
                            .add(jTadresse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(jTnom)
                            .add(jTid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(101, 101, 101)
                        .add(jLabel12)))
                .add(240, 240, 240)
                .add(jButton1)
                .add(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabel12)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLid)
                    .add(jTid))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLnom)
                    .add(jTnom))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLadresse)
                    .add(jTadresse))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLcodepostal)
                            .add(jButton1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLresnom)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLresprenom)
                        .add(26, 26, 26))
                    .add(layout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jTcodepostal)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTville)
                            .add(jLville))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTtelephone)
                            .add(jLtelephone))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTmail)
                            .add(jLmail))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTtype)
                            .add(jLtype))
                        .add(7, 7, 7)
                        .add(jLabel13)
                        .add(40, 40, 40)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTresciv)
                            .add(jLresciv))
                        .add(27, 27, 27)
                        .add(jTresnom)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTresprenom)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String id = jTid.getText();
       String nom = jTnom.getText();
       String adresse = jTadresse.getText();
       String codepostal = jTcodepostal.getText();
       String telephone = jTtelephone.getText();
       String ville = jTville.getText();
       String mail = jTmail.getText();
       byte type = Byte.parseByte(jTtype.getText());
       String resid = jTresciv.getText();
       String resnom = jTresnom.getText();
       String resprenom = jTresprenom.getText();
       
       
        Etablissement unnouveletablissement = new Etablissement(id, nom, adresse, codepostal,telephone,ville ,mail,type,resid,resnom,resprenom);  
        /**/        Transaction tx = fPrincipal.getSession().beginTransaction();
        fPrincipal.getSession().save(unnouveletablissement);
        tx.commit();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws java.lang.InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pEtablissementAjout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pEtablissementAjout().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLadresse;
    private javax.swing.JLabel jLcodepostal;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLmail;
    private javax.swing.JLabel jLnom;
    private javax.swing.JLabel jLresciv;
    private javax.swing.JLabel jLresnom;
    private javax.swing.JLabel jLresprenom;
    private javax.swing.JLabel jLtelephone;
    private javax.swing.JLabel jLtype;
    private javax.swing.JLabel jLville;
    private javax.swing.JTextField jTadresse;
    private javax.swing.JTextField jTcodepostal;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTmail;
    private javax.swing.JTextField jTnom;
    private javax.swing.JTextField jTresciv;
    private javax.swing.JTextField jTresnom;
    private javax.swing.JTextField jTresprenom;
    private javax.swing.JTextField jTtelephone;
    private javax.swing.JTextField jTtype;
    private javax.swing.JTextField jTville;
    // End of variables declaration//GEN-END:variables
}
