/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modele.Etablissement;
import modele.Typechambre;
import modele.Offre;
import org.hibernate.Query;

/**
 *
 * @author FLORIAN
 */
public class pHebergement extends javax.swing.JPanel {

    /**
     * Creates new form pHebergement
     */
    public pHebergement() {
        initComponents();
        afficherHebergement();
        insertTableau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableHebergement = new javax.swing.JTable();
        NomGroupe = new javax.swing.JLabel();
        SelectEtablissement = new javax.swing.JComboBox();

        TableHebergement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Capacité", "Nombre de chambres"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableHebergement.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TableHebergementComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(TableHebergement);

        NomGroupe.setText("Par etablissement :");

        SelectEtablissement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectEtablissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEtablissementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(NomGroupe)
                        .addGap(18, 18, 18)
                        .addComponent(SelectEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomGroupe)
                    .addComponent(SelectEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectEtablissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEtablissementActionPerformed
        // TODO add your handling code here:
        SelectEtablissement.getName();
    }//GEN-LAST:event_SelectEtablissementActionPerformed

    private void TableHebergementComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TableHebergementComponentAdded
        // TODO add your handling code here:
        TableHebergement.getName();
    }//GEN-LAST:event_TableHebergementComponentAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomGroupe;
    private javax.swing.JComboBox SelectEtablissement;
    private javax.swing.JTable TableHebergement;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void afficherHebergement() {
        SelectEtablissement.removeAllItems();
        String sReq = "FROM Etablissement";
        fPrincipal.getSession().beginTransaction();
        Query q = fPrincipal.getSession().createQuery(sReq);
        Iterator Etablissement = q.iterate();
        while (Etablissement.hasNext()) {
            Etablissement unEtablissement = (Etablissement) Etablissement.next();
            SelectEtablissement.addItem(unEtablissement.getNom());}
    }

    private void insertTableau() {
        String sNbre;
        String sQuery;
        int l=0;
        int inbligne;
        int i;
        sNbre = (String) TableHebergement.getSelectedItem();
        sNbre = sNbre.replace("""", """");
        sQuery = "FROM Typechambre" + sNbre +""
            }
        }
}