package modele;
// Generated 3 avr. 2013 10:08:09 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttributionId generated by hbm2java
 */
@Embeddable
public class AttributionId  implements java.io.Serializable {


     private String idEtab;
     private String idTypeChambre;
     private String idGroupe;

    public AttributionId() {
    }

    public AttributionId(String idEtab, String idTypeChambre, String idGroupe) {
       this.idEtab = idEtab;
       this.idTypeChambre = idTypeChambre;
       this.idGroupe = idGroupe;
    }
   

    @Column(name="idEtab", nullable=false, length=8)
    public String getIdEtab() {
        return this.idEtab;
    }
    
    public void setIdEtab(String idEtab) {
        this.idEtab = idEtab;
    }

    @Column(name="idTypeChambre", nullable=false, length=2)
    public String getIdTypeChambre() {
        return this.idTypeChambre;
    }
    
    public void setIdTypeChambre(String idTypeChambre) {
        this.idTypeChambre = idTypeChambre;
    }

    @Column(name="idGroupe", nullable=false, length=4)
    public String getIdGroupe() {
        return this.idGroupe;
    }
    
    public void setIdGroupe(String idGroupe) {
        this.idGroupe = idGroupe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttributionId) ) return false;
		 AttributionId castOther = ( AttributionId ) other; 
         
		 return ( (this.getIdEtab()==castOther.getIdEtab()) || ( this.getIdEtab()!=null && castOther.getIdEtab()!=null && this.getIdEtab().equals(castOther.getIdEtab()) ) )
 && ( (this.getIdTypeChambre()==castOther.getIdTypeChambre()) || ( this.getIdTypeChambre()!=null && castOther.getIdTypeChambre()!=null && this.getIdTypeChambre().equals(castOther.getIdTypeChambre()) ) )
 && ( (this.getIdGroupe()==castOther.getIdGroupe()) || ( this.getIdGroupe()!=null && castOther.getIdGroupe()!=null && this.getIdGroupe().equals(castOther.getIdGroupe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEtab() == null ? 0 : this.getIdEtab().hashCode() );
         result = 37 * result + ( getIdTypeChambre() == null ? 0 : this.getIdTypeChambre().hashCode() );
         result = 37 * result + ( getIdGroupe() == null ? 0 : this.getIdGroupe().hashCode() );
         return result;
   }   


}


