package modele;
// Generated 3 avr. 2013 10:08:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etablissement generated by hbm2java
 */
@Entity
@Table(name="etablissement"
    ,catalog="festival"
)
public class Etablissement  implements java.io.Serializable {


     private String id;
     private String nom;
     private String adresseRue;
     private String codePostal;
     private String ville;
     private String tel;
     private String adresseElectronique;
     private byte type;
     private String civiliteResponsable;
     private String nomResponsable;
     private String prenomResponsable;
     private Set offres = new HashSet(0);

    public Etablissement() {
    }

	
    public Etablissement(String id, String nom, String adresseRue, String codePostal, String ville, String tel, byte type, String civiliteResponsable, String nomResponsable) {
        this.id = id;
        this.nom = nom;
        this.adresseRue = adresseRue;
        this.codePostal = codePostal;
        this.ville = ville;
        this.tel = tel;
        this.type = type;
        this.civiliteResponsable = civiliteResponsable;
        this.nomResponsable = nomResponsable;
    }
    public Etablissement(String id, String nom, String adresseRue, String codePostal, String ville, String tel, String adresseElectronique, byte type, String civiliteResponsable, String nomResponsable, String prenomResponsable, Set offres) {
       this.id = id;
       this.nom = nom;
       this.adresseRue = adresseRue;
       this.codePostal = codePostal;
       this.ville = ville;
       this.tel = tel;
       this.adresseElectronique = adresseElectronique;
       this.type = type;
       this.civiliteResponsable = civiliteResponsable;
       this.nomResponsable = nomResponsable;
       this.prenomResponsable = prenomResponsable;
       this.offres = offres;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=8)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="nom", nullable=false, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @Column(name="adresseRue", nullable=false, length=45)
    public String getAdresseRue() {
        return this.adresseRue;
    }
    
    public void setAdresseRue(String adresseRue) {
        this.adresseRue = adresseRue;
    }
    
    @Column(name="codePostal", nullable=false, length=5)
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    
    @Column(name="ville", nullable=false, length=35)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    
    @Column(name="tel", nullable=false, length=13)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="adresseElectronique", length=70)
    public String getAdresseElectronique() {
        return this.adresseElectronique;
    }
    
    public void setAdresseElectronique(String adresseElectronique) {
        this.adresseElectronique = adresseElectronique;
    }
    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    
    @Column(name="civiliteResponsable", nullable=false, length=12)
    public String getCiviliteResponsable() {
        return this.civiliteResponsable;
    }
    
    public void setCiviliteResponsable(String civiliteResponsable) {
        this.civiliteResponsable = civiliteResponsable;
    }
    
    @Column(name="nomResponsable", nullable=false, length=25)
    public String getNomResponsable() {
        return this.nomResponsable;
    }
    
    public void setNomResponsable(String nomResponsable) {
        this.nomResponsable = nomResponsable;
    }
    
    @Column(name="prenomResponsable", length=25)
    public String getPrenomResponsable() {
        return this.prenomResponsable;
    }
    
    public void setPrenomResponsable(String prenomResponsable) {
        this.prenomResponsable = prenomResponsable;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etablissement")
    public Set getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set offres) {
        this.offres = offres;
    }




}


