package modele;
// Generated 3 avr. 2013 10:08:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offre generated by hbm2java
 */
@Entity
@Table(name="offre"
    ,catalog="festival"
)
public class Offre  implements java.io.Serializable {


     private OffreId id;
     private Typechambre typechambre;
     private Etablissement etablissement;
     private int nombreChambres;
     private Set attributions = new HashSet(0);

    public Offre() {
    }

	
    public Offre(OffreId id, Typechambre typechambre, Etablissement etablissement, int nombreChambres) {
        this.id = id;
        this.typechambre = typechambre;
        this.etablissement = etablissement;
        this.nombreChambres = nombreChambres;
    }
    public Offre(OffreId id, Typechambre typechambre, Etablissement etablissement, int nombreChambres, Set attributions) {
       this.id = id;
       this.typechambre = typechambre;
       this.etablissement = etablissement;
       this.nombreChambres = nombreChambres;
       this.attributions = attributions;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idEtab", column=@Column(name="idEtab", nullable=false, length=8) ), 
        @AttributeOverride(name="idTypeChambre", column=@Column(name="idTypeChambre", nullable=false, length=2) ) } )
    public OffreId getId() {
        return this.id;
    }
    
    public void setId(OffreId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTypeChambre", nullable=false, insertable=false, updatable=false)
    public Typechambre getTypechambre() {
        return this.typechambre;
    }
    
    public void setTypechambre(Typechambre typechambre) {
        this.typechambre = typechambre;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEtab", nullable=false, insertable=false, updatable=false)
    public Etablissement getEtablissement() {
        return this.etablissement;
    }
    
    public void setEtablissement(Etablissement etablissement) {
        this.etablissement = etablissement;
    }
    
    @Column(name="nombreChambres", nullable=false)
    public int getNombreChambres() {
        return this.nombreChambres;
    }
    
    public void setNombreChambres(int nombreChambres) {
        this.nombreChambres = nombreChambres;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="offre")
    public Set getAttributions() {
        return this.attributions;
    }
    
    public void setAttributions(Set attributions) {
        this.attributions = attributions;
    }




}


