package modele;
// Generated 3 avr. 2013 10:08:09 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OffreId generated by hbm2java
 */
@Embeddable
public class OffreId  implements java.io.Serializable {


     private String idEtab;
     private String idTypeChambre;

    public OffreId() {
    }

    public OffreId(String idEtab, String idTypeChambre) {
       this.idEtab = idEtab;
       this.idTypeChambre = idTypeChambre;
    }
   

    @Column(name="idEtab", nullable=false, length=8)
    public String getIdEtab() {
        return this.idEtab;
    }
    
    public void setIdEtab(String idEtab) {
        this.idEtab = idEtab;
    }

    @Column(name="idTypeChambre", nullable=false, length=2)
    public String getIdTypeChambre() {
        return this.idTypeChambre;
    }
    
    public void setIdTypeChambre(String idTypeChambre) {
        this.idTypeChambre = idTypeChambre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OffreId) ) return false;
		 OffreId castOther = ( OffreId ) other; 
         
		 return ( (this.getIdEtab()==castOther.getIdEtab()) || ( this.getIdEtab()!=null && castOther.getIdEtab()!=null && this.getIdEtab().equals(castOther.getIdEtab()) ) )
 && ( (this.getIdTypeChambre()==castOther.getIdTypeChambre()) || ( this.getIdTypeChambre()!=null && castOther.getIdTypeChambre()!=null && this.getIdTypeChambre().equals(castOther.getIdTypeChambre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEtab() == null ? 0 : this.getIdEtab().hashCode() );
         result = 37 * result + ( getIdTypeChambre() == null ? 0 : this.getIdTypeChambre().hashCode() );
         return result;
   }   


}


