package modele;
// Generated 3 avr. 2013 10:08:09 by Hibernate Tools 3.2.1.GA


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Typechambre generated by hbm2java
 */
@Entity
@Table(name="typechambre"
    ,catalog="festival"
)
public class Typechambre  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


     private String id;
     private String libelle;
     private Set offres = new HashSet(0);

    public Typechambre() {
    }

	
    public Typechambre(String id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public Typechambre(String id, String libelle, Set offres) {
       this.id = id;
       this.libelle = libelle;
       this.offres = offres;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false, length=2)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        String oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }
    
    @Column(name="libelle", nullable=false, length=15)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        String oldLibelle = this.libelle;
        this.libelle = libelle;
        changeSupport.firePropertyChange("libelle", oldLibelle, libelle);
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="typechambre")
    public Set getOffres() {
        return this.offres;
    }
    
    public void setOffres(Set offres) {
        this.offres = offres;
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }




}


